# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Kisun\Desktop\first-order-ui\src\main\resources\base\pathdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(601, 274)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.source_image_path_edit = QtWidgets.QLineEdit(self.groupBox_3)
        self.source_image_path_edit.setObjectName("source_image_path_edit")
        self.horizontalLayout_2.addWidget(self.source_image_path_edit)
        self.browse_image_button = QtWidgets.QPushButton(self.groupBox_3)
        self.browse_image_button.setObjectName("browse_image_button")
        self.horizontalLayout_2.addWidget(self.browse_image_button)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.source_image_path_edit_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.source_image_path_edit_2.setObjectName("source_image_path_edit_2")
        self.horizontalLayout_3.addWidget(self.source_image_path_edit_2)
        self.browse_image_button_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.browse_image_button_2.setObjectName("browse_image_button_2")
        self.horizontalLayout_3.addWidget(self.browse_image_button_2)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Change checkpoint and config paths"))
        self.label.setText(_translate("Dialog", "You can change the checkpoint and config files this program uses here. This is typically set to vox-adv-cpk.pth.tar for the checkpoint file and vox-256.yaml for the config file."))
        self.label_2.setText(_translate("Dialog", "If you downloaded this program with the checkpoint packaged, the checkpoint should already be set below. If not, then you will need to download a checkpoint manually and set it here."))
        self.groupBox_3.setTitle(_translate("Dialog", "Checkpoint"))
        self.browse_image_button.setText(_translate("Dialog", "Browse..."))
        self.groupBox_4.setTitle(_translate("Dialog", "Config"))
        self.browse_image_button_2.setText(_translate("Dialog", "Browse..."))
